version: '3.4'

services:
  # Movies API
  movies:
    image: localhost:5000/moviesservice:V2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80

  # MySQL database
  db:
    container_name: "movies_db"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"