on:
  push:
    branches: ["main", "ci-cd-pipeline"]

jobs:
  run-load-test:
    name: Set up Grafana & InfluxDB
    runs-on: self-hosted
    steps:
      - name: Setup environment
        run: ./scripts/run_load_test.ps1