name: k6 Load Test
on:
  push:
    branches:
      - "ci-cd-pipeline"
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ./tests/load_test.js