# name: Run K6 load test
# on:
#   push:
#     branches: ["main", "ci-cd-pipeline"]

# jobs:
#   setup-grafana-influx:
#     name: K6 Load Test
#     runs-on: self-hosted
#     steps:
#       - name: Setup environment
#         run: ./scripts/run_load_test