k6_load_test:
  name: k6 load test
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout
    - name: Run local k6 test
      uses: grafana/k6-action@v1.4.3
      with:
        filename: ./tests/load_test.js