name: movies-azure-deployment
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: general-kinoroom-prod-westeu-001
    AZURE_CONTAINER_REGISTRY: kinoroomregistry
    CLUSTER_NAME: kinoroom-cluster
    CLUSTER_RESOURCE_GROUP: kinoroom-cluster_group
    CONTAINER_NAME: movies_api
    DEPLOYMENT_MANIFEST_PATH: |
        ./manifests/deployment.yml
        ./manifests/ingress.yml
        ./manifests/service.yml
        ./manifests/autoscaler.yml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Build and push image to ACR
              run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./Dockerfile ./
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: self-hosted
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: default
