name: .NET

on:
  push:
    branches: [ "main", "ci-cd-pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: actions/checkout@v2
  build-deploy-local:
    needs: [build]
    runs-on: self-hosted    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push image to local registry
      id: build-docker-image
      run: |
        docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ${{ secrets.REGISTRY_URL }}/movies-api:latest --label dockerfile-path=Dockerfile
        docker push ${{ secrets.REGISTRY_URL }}/movies-api:latest
    
    - name: Deploy to local Kubernetes cluster
      id: deploy-local-cluster
      run: |
        kubectl apply -f ./manifests/deployment.yml
        kubectl apply -f ./manifests/service.yml
        kubectl apply -f ./manifests/ingress.yml
        kubectl apply -f ./manifests/autoscaler.yml